<script setup lang="ts">
import { reactive } from 'vue'
import type { StationModel } from "@/types/station"

const stations = reactive<StationModel[]>([
    {
        station_name: "藏墩二站",
        station_location: "芜湖市鸠江区沈巷镇凤城行政村",
        birth_day: 2004,
        suozailiuyu: "长江",
        zhuangji: 5,
        bengzhangongneng: "排灌结合",
        shejipailaoyangchen: 5,
        gaizaonianfen: "",
        suozaishuixi: "藏墩二站片",
        zongrongliang: 900,
        shouyifanwei: 18,
        shejipailaoshuiwei: 7.1,
        gailaoleixing: "",
        suozaiweikou: "十四连圩",
        liuliang: 12,
        shouyimianji: 1.4,
        pailaozuigaochushuiwei: 12.1,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-1250-35",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 338,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 260,
        yalixiang_changdu: 65.5,
        yalixiang_koujing: "1.7X2.2双孔",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0717.JPG" },
            { title: "泵站近景", src: "DSC_0726.JPG" },
            { title: "主厂房", src: "DSC_0733.JPG" },
            { title: "开关柜", src: "DSC_0739.JPG" },
            { title: "进水闸", src: "DSC_0751.JPG" },
            { title: "出水闸", src: "DSC_0719.JPG" }
        ]
    },
    {
        station_name: "藏墩一站",
        station_location: "芜湖市鸠江区沈巷镇南埂行政村",
        birth_day: 1965,
        suozailiuyu: "裕溪河",
        zhuangji: 7,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5,
        gaizaonianfen: "2002 年",
        suozaishuixi: "藏墩一站片",
        zongrongliang: 1085,
        shouyifanwei: 26,
        shejipailaoshuiwei: 7.1,
        gailaoleixing: "改建",
        suozaiweikou: "十四连圩",
        liuliang: 15.4,
        shouyimianji: 1.5,
        pailaozuigaochushuiwei: 12.1,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-1600-35",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 229.5,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 310,
        yalixiang_changdu: 35,
        yalixiang_koujing: "2X2.5 双孔",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0811.JPG" },
            { title: "主厂房", src: "DSC_0820.JPG" },
            { title: "开关柜", src: "DSC_0828.JPG" },
            { title: "进水闸", src: "DSC_0815.JPG" },
            { title: "出水闸", src: "DSC_0808.JPG" },
        ],
    },
    {
        station_name: "大桥泵站",
        station_location: "芜湖市鸠江区沈巷镇灯塔行政村",
        birth_day: 1973,
        suozailiuyu: "牛屯河",
        zhuangji: 3,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5.8,
        gaizaonianfen: "2015 年",
        suozaishuixi: "大桥站片",
        zongrongliang: 390,
        shouyifanwei: 7,
        shejipailaoshuiwei: 6.8,
        gailaoleixing: "技改",
        suozaiweikou: "练钢圩",
        liuliang: 4.5,
        shouyimianji: 0.3,
        pailaozuigaochushuiwei: 12.6,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S11-M-360/10",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL12-10",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "700ZLB-100",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 90,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 87,
        yalixiang_changdu: 43,
        yalixiang_koujing: "1.9X2",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0914.JPG" },
            { title: "主厂房", src: "DSC_0907.JPG" },
            { title: "开关柜", src: "DSC_0913.JPG" },
            { title: "进水闸", src: "DSC_0906.JPG" },
            { title: "出水闸", src: "DSC_0916.JPG" },
        ],
    },
    {
        station_name: "河南汤站",
        station_location: "芜湖市鸠江区沈巷镇五显社区",
        birth_day: 1987,
        suozailiuyu: "牛屯河",
        zhuangji: 2,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5,
        gaizaonianfen: "2015 年",
        suozaishuixi: "河南汤水系",
        zongrongliang: 260,
        shouyifanwei: 4,
        shejipailaoshuiwei: 7.2,
        gailaoleixing: "技改",
        suozaiweikou: "练钢圩",
        liuliang: 3,
        shouyimianji: 0.2,
        pailaozuigaochushuiwei: 12.2,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S11-M-400/10",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL12-10",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "700ZLB-100",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 55,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 87,
        yalixiang_changdu: 43,
        yalixiang_koujing: "1.4X1.6",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0924.JPG" },
            { title: "主厂房", src: "DSC_0929.JPG" },
            { title: "开关柜", src: "DSC_0935.JPG" },
            { title: "进水闸", src: "DSC_0936.JPG" },
            { title: "出水闸", src: "DSC_0920.JPG" },
        ],
    },
    {
        station_name: "黄山寺排灌站（老站）",
        station_location: "芜湖市鸠江区沈巷镇黄山寺社区",
        birth_day: 1958,
        suozailiuyu: "长江",
        zhuangji: 5,
        bengzhangongneng: "排灌结合",
        shejipailaoyangchen: 5.8,
        gaizaonianfen: "1991 年",
        suozaishuixi: "长河、北港河",
        zongrongliang: 1300,
        shouyifanwei: 41,
        shejipailaoshuiwei: 7.2,
        gailaoleixing: "更换机、泵",
        suozaiweikou: "练钢圩",
        liuliang: 16.5,
        shouyimianji: 5,
        pailaozuigaochushuiwei: 12.8,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S7-2000-35",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-10",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-5.8",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 220,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 650,
        yalixiang_changdu: 44,
        yalixiang_koujing: "2.2X3",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_1059.JPG" },
            { title: "主厂房", src: "DSC_1075.JPG" },
            { title: "控制室", src: "DSC_1079.JPG" },
            { title: "进水闸", src: "DSC_1067.JPG" },
            { title: "出水闸", src: "DSC_1056.JPG" },
        ],
    },
    {
        station_name: "黄山寺排灌站（新站）",
        station_location: "芜湖市鸠江区沈巷镇黄山寺社区",
        birth_day: 2004,
        suozailiuyu: "长江",
        zhuangji: 5,
        bengzhangongneng: "排灌结合",
        shejipailaoyangchen: 7.2,
        gaizaonianfen: " ",
        suozaishuixi: "长河、北港河",
        zongrongliang: 2500,
        shouyifanwei: 41,
        shejipailaoshuiwei: 7.0,
        gailaoleixing: " ",
        suozaiweikou: "练钢圩",
        liuliang: 30,
        shouyimianji: 5,
        pailaozuigaochushuiwei: 14.2,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-3150-35",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL128-8",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 250,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 350,
        yalixiang_changdu: 44,
        yalixiang_koujing: "2.7X3",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_1062.JPG" },
            { title: "主厂房", src: "DSC_1089.JPG" },
            { title: "进水闸", src: "DSC_1074.JPG" },
            { title: "出水闸", src: "DSC_1058.JPG" },
        ],
    },
    {
        station_name: "老坝泵站",
        station_location: "芜湖市鸠江区沈巷镇双坝行政村",
        birth_day: 1968,
        suozailiuyu: "裕溪河",
        zhuangji: 5,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5.0,
        gaizaonianfen: "2008 年",
        suozaishuixi: "东港水系",
        zongrongliang: 775,
        shouyifanwei: 21,
        shejipailaoshuiwei: 7.0,
        gailaoleixing: "重建",
        suozaiweikou: "十四连圩",
        liuliang: 11,
        shouyimianji: 1.2,
        pailaozuigaochushuiwei: 12,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-1000-10",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 230,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 330,
        yalixiang_changdu: 31,
        yalixiang_koujing: "3.3X3.3",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0848.JPG" },
            { title: "主厂房", src: "DSC_0856.JPG" },
            { title: "开关柜", src: "DSC_0861.JPG" },
            { title: "进水闸", src: "DSC_0866.JPG" },
            { title: "出水闸", src: "DSC_0851.JPG" },
        ],
    },
    {
        station_name: "童子圩泵站",
        station_location: "芜湖市鸠江区沈巷镇孙庄行政村",
        birth_day: 1987,
        suozailiuyu: "牛屯河",
        zhuangji: 5,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5.8,
        gaizaonianfen: "1993 年",
        suozaishuixi: "童子圩片",
        zongrongliang: 275,
        shouyifanwei: 5,
        shejipailaoshuiwei: 7.0,
        gailaoleixing: "扩建",
        suozaiweikou: "练钢圩",
        liuliang: 2.75,
        shouyimianji: 0.3,
        pailaozuigaochushuiwei: 12.8,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S11-M-400/10",
        dianji_leixing: "立式",
        dianji_xinghao: "Y315M-10",
        shuibeng_leixing: "卧式",
        shuibeng_xinghao: "500HW-6",
        zhujifang_leixing: "分基型",
        zhujifang_mianji: 106,
        guanlifang_leixing: "砖瓦",
        guanlifang_mianji: 60,
        yalixiang_changdu: 43,
        yalixiang_koujing: "1.4X1.6",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0945.JPG" },
            { title: "主厂房", src: "DSC_0946.JPG" },
            { title: "进水渠", src: "DSC_0953.JPG" },
        ],
    },
    {
        station_name: "新坝泵站",
        station_location: "芜湖市鸠江区沈巷镇新坝行政村",
        birth_day: 2000,
        suozailiuyu: "裕溪河",
        zhuangji: 2,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 4.8,
        gaizaonianfen: " ",
        suozaishuixi: "新坝片",
        zongrongliang: 360,
        shouyifanwei: 9,
        shejipailaoshuiwei: 7.2,
        gailaoleixing: " ",
        suozaiweikou: "十四连圩",
        liuliang: 5,
        shouyimianji: 0.6,
        pailaozuigaochushuiwei: 12.0,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S20-M-630/10",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-6",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 65,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 50,
        yalixiang_changdu: 45,
        yalixiang_koujing: "1.8X2",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0835.JPG" },
            { title: "主厂房", src: "DSC_0841.JPG" },
            { title: "开关柜", src: "DSC_0843.JPG" },
            { title: "进水闸", src: "DSC_0845.JPG" },
            { title: "出水闸", src: "DSC_0833.JPG" },
        ],
    },
    {
        station_name: "姚郭泵站",
        station_location: "芜湖市鸠江区沈巷镇双河行政村",
        birth_day: 1958,
        suozailiuyu: "牛屯河",
        zhuangji: 6,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 5.8,
        gaizaonianfen: "2015 年",
        suozaishuixi: "十字中心河",
        zongrongliang: 1080,
        shouyifanwei: 21,
        shejipailaoshuiwei: 7.0,
        gailaoleixing: "移址重建",
        suozaiweikou: "练钢圩",
        liuliang: 13.4,
        shouyimianji: 1.2,
        pailaozuigaochushuiwei: 12.8,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S11-M-800/10",
        dianji_leixing: "立式",
        dianji_xinghao: "YSL600-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "湿室型",
        zhujifang_mianji: 237,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 280,
        yalixiang_changdu: 50,
        yalixiang_koujing: "1.8X2.5 双孔",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0875.JPG" },
            { title: "主厂房", src: "DSC_0892.JPG" },
            { title: "开关柜", src: "DSC_0902.JPG" },
            { title: "进水闸", src: "DSC_0886.JPG" },
            { title: "出水闸", src: "DSC_0877.JPG" },
        ],
    },
    {
        station_name: "雍镇泵站",
        station_location: "芜湖市鸠江区沈巷镇雍镇社区",
        birth_day: 1954,
        suozailiuyu: "裕溪河",
        zhuangji: 4,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 4.8,
        gaizaonianfen: "2008 年",
        suozaishuixi: "雍镇片",
        zongrongliang: 620,
        shouyifanwei: 16,
        shejipailaoshuiwei: 7.2,
        gailaoleixing: "移址重建",
        suozaiweikou: "十四连圩",
        liuliang: 8.8,
        shouyimianji: 1.2,
        pailaozuigaochushuiwei: 12.0,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-800-35",
        dianji_leixing: "立式",
        dianji_xinghao: "JSL14-12",
        shuibeng_leixing: "立式",
        shuibeng_xinghao: "900ZLB-85",
        zhujifang_leixing: "干室型",
        zhujifang_mianji: 198,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 444,
        yalixiang_changdu: 45,
        yalixiang_koujing: "2.3X2.5 双孔",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0799.JPG" },
            { title: "主厂房", src: "DSC_0782.JPG" },
            { title: "开关柜", src: "DSC_0786.JPG" },
            { title: "进水闸", src: "DSC_0791.JPG" },
            { title: "出水闸", src: "DSC_0803.JPG" },
        ],
    },
    {
        station_name: "裕溪泵站",
        station_location: "芜湖市鸠江区沈巷镇裕溪社区",
        birth_day: 1958,
        suozailiuyu: "长江",
        zhuangji: 6,
        bengzhangongneng: "排涝",
        shejipailaoyangchen: 4.8,
        gaizaonianfen: "2009 年",
        suozaishuixi: "永安河",
        zongrongliang: 540,
        shouyifanwei: 13,
        shejipailaoshuiwei: 7.2,
        gailaoleixing: "改建",
        suozaiweikou: "十四连圩",
        liuliang: 6.0,
        shouyimianji: 1.0,
        pailaozuigaochushuiwei: 12.0,
        bianyaqi_leixing: "油浸",
        bianyaqi_xinghao: "S9-800-35",
        dianji_leixing: "立式",
        dianji_xinghao: "Y355M2-12",
        shuibeng_leixing: "卧式",
        shuibeng_xinghao: "600HM-7",
        zhujifang_leixing: "分基型",
        zhujifang_mianji: 284,
        guanlifang_leixing: "砖混",
        guanlifang_mianji: 620,
        yalixiang_changdu: 49,
        yalixiang_koujing: "2X2",
        yalixiang_jiegou: "钢混",
        station_pic_list: [
            { title: "泵站远景", src: "DSC_0756.JPG" },
            { title: "主厂房", src: "DSC_0774.JPG" },
            { title: "开关柜", src: "DSC_0760.JPG" },
            { title: "进水闸", src: "DSC_0766.JPG" },
            { title: "出水闸", src: "DSC_0753.JPG" },
        ],
    }
])
</script>

<template>
    <div class="mx-auto w-7xl">
        <div class="flex items-center py-4">
            <span class="h-5 w-1 rounded bg-primary mr-3"></span>
            <div>
                <p class="text-xs text-gray-500">Station Info</p>
                <h2 class="text-lg font-semibold text-gray-900">泵站信息</h2>
            </div>
        </div>

        <div class=" grid grid-cols-4 gap-4">
            <div v-for="(station, index) in stations" :key="index"
                class="bg-white rounded-lg shadow-xs shadow-slate-200 ring-1 ring-border flex flex-col overflow-hidden transition-transform duration-300 hover:-translate-y-2">
                <div class="overflow-hidden h-52">
                    <img class="w-full h-full"
                        src="http://100.68.9.83:8666/image/289ce6f95488446f96c33fa21d39fef4.JPG?_type=thumb" alt="pic">
                </div>
                <div class="p-4 flex flex-col gap-2">
                    <div class="flex items-center">
                        <div class="h-4 w-0.5 bg-primary mr-3 rounded"></div>
                        <div class="font-bold text-red-800">{{
                            station.station_name }}
                        </div>
                    </div>
                    <div class="text-l text-slate-400">机组 {{
                        station.zhuangji }} 台套
                    </div>
                    <div class="text-l text-slate-400">容量 {{ station.zongrongliang }}kw 流量 {{ station.liuliang
                        }}m<sup>3</sup>/s
                    </div>
                    <a href="#" class="text-red-700 text-sm text-right px-4 flex justify-end">查看详情
                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
                            stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</template>